"""Export a reasons network as beliefs.md-compatible markdown."""

from .metadata import build_meta
from .network import Network


def export_markdown(network: Network, repos: dict[str, str] | None = None) -> str:
    """Generate a beliefs.md-compatible markdown file from the network.

    Args:
        network: The network to export
        repos: Optional repo name → path mapping for the Repos section

    Nodes are sorted: IN first (alphabetical), then OUT (alphabetical).
    Includes YAML frontmatter with metadata if available.
    """
    meta = build_meta(
        project_name=network.meta.get("project_name", ""),
        node_count=len(network.nodes),
        created_at=network.meta.get("created_at", ""),
    )

    lines = [
        "---",
        f'schema_version: "{meta["schema_version"]}"',
        f"project_name: \"{meta['project_name']}\"" if meta["project_name"] else "project_name:",
        f'updated_at: "{meta["updated_at"]}"',
        f"node_count: {meta['node_count']}",
        f"generator: {meta['generator']}",
        "---",
        "",
        "# Belief Registry",
        "<!-- Generated by reasons export-markdown. Do not edit — operate through reasons. -->",
        "",
    ]

    if repos:
        lines.append("## Repos")
        for name, path in sorted(repos.items()):
            lines.append(f"- {name}: {path}")
        lines.append("")

    lines.extend([
        "## Claims",
        "",
    ])

    # Sort: IN first, then OUT, alphabetical within each group
    nodes = sorted(network.nodes.values(), key=lambda n: (n.truth_value != "IN", n.id))

    for node in nodes:
        # Map truth value to beliefs status
        status = node.truth_value
        if status == "OUT" and (node.metadata.get("stale_reason") or node.metadata.get("retract_reason")):
            status = "STALE"

        # Get beliefs_type from metadata, default to DERIVED or OBSERVATION
        btype = node.metadata.get("beliefs_type", "")
        if not btype:
            btype = "DERIVED" if node.justifications else "OBSERVATION"

        lines.append(f"### {node.id} [{status}] {btype}")
        lines.append(node.text)

        if node.source:
            lines.append(f"- Source: {node.source}")
        if node.source_url:
            lines.append(f"- Source URL: {node.source_url}")
        if node.metadata.get("source_type"):
            lines.append(f"- Source type: {node.metadata['source_type']}")
        if node.source_hash:
            lines.append(f"- Source hash: {node.source_hash}")
        if node.date:
            lines.append(f"- Date: {node.date}")

        # Collect all antecedents across justifications as depends_on
        all_deps = []
        all_unless = []
        all_defeaters = []
        for j in node.justifications:
            for a in j.antecedents:
                if a not in all_deps:
                    all_deps.append(a)
            for o in j.outlist:
                o_node = network.nodes.get(o)
                if o_node and o_node.metadata.get("defeats_node") == node.id:
                    dtype = o_node.metadata.get("defeater_type", "defeater")
                    rtype = o_node.metadata.get("defeat_reason_type", "")
                    if o not in [d[0] for d in all_defeaters]:
                        all_defeaters.append((o, dtype, rtype))
                elif o not in all_unless:
                    all_unless.append(o)
        if all_deps:
            lines.append(f"- Depends on: {', '.join(all_deps)}")
        if all_unless:
            lines.append(f"- Unless: {', '.join(all_unless)}")
        if all_defeaters:
            for d_id, d_type, r_type in all_defeaters:
                label = f"{d_type}, {r_type}" if r_type else d_type
                lines.append(f"- Defeated by: {d_id} ({label})")

        # Retraction reason — from retract --reason or imported stale_reason
        retract_reason = node.metadata.get("retract_reason") or node.metadata.get("stale_reason")
        if status in ("STALE", "OUT") and retract_reason:
            lines.append(f"- Stale reason: {retract_reason}")
        if node.metadata.get("duplicate_of"):
            lines.append(f"- Duplicate of: {node.metadata['duplicate_of']}")
        if node.metadata.get("superseded_by"):
            lines.append(f"- Superseded by: {node.metadata['superseded_by']}")
        if node.metadata.get("accepted_pr"):
            lines.append(f"- Accepted PR: {node.metadata['accepted_pr']}")

        lines.append("")

    # Nogoods section
    if network.nogoods:
        lines.append("## Nogoods")
        lines.append("")
        for ng in network.nogoods:
            lines.append(f"### {ng.id}")
            if ng.discovered:
                lines.append(f"- Discovered: {ng.discovered}")
            if ng.resolution:
                lines.append(f"- Resolution: {ng.resolution}")
            lines.append(f"- Affects: {', '.join(ng.nodes)}")
            lines.append("")

    return "\n".join(lines)
